version: "3"

services:
  db:
    image: "postgres:11"
    container_name: "db-ismoil-postgres"
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "54320:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
